spring:
  cloud:
    gateway:
      routes:
        # 弹幕服务
        - id: Danmaku_route
          uri: lb://Danmaku
          predicates:
            - Path=/api/danmaku/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # 对象存储
        - id: OSS_route
          uri: lb://OSS
          predicates:
            - Path=/api/uploads/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # 搜索
        - id: Search_router
          uri: lb://Search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # 核心服务
        - id: Evaluation_route
          uri: lb://Evaluation
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
