server:
  port: 8087
spring:
  cloud:
    nacos:
      server-addr: 192.168.43.131:8848
  kafka:
    bootstrap-servers:
      - 192.168.43.131:9092
    consumer:
      group-id: Email
    listener:
      missing-topics-fatal: false
#  mail:
#    host: smtp.qq.com
#    username:
#    password:
#    protocol: smtp

