minio:
  server: http://192.168.1.108:9000
  accessKey: admin
  secretKey: pzw123456
  bucketName: homework
  # 300 秒
  expiry: 300
server:
  port: 8095

spring:
  cloud:
    nacos:
      server-addr: 192.168.43.131:8848
  servlet:
    multipart:
      enabled: true
      max-file-size: 204800MB
      max-request-size: 102400000000MB
