alibaba:
  canal:
    host:
      - 192.168.43.131:11111
    destination: example
    database: homework_evaluation
    username: root
    password: 123456

spring:
  cloud:
    nacos:
      server-addr: 192.168.43.131:8848
