spring:
  cloud:
    nacos:
      server-addr: 192.168.43.131:8848
  kafka:
    bootstrap-servers:
      - 192.168.43.131:9092
    consumer:
      group-id: Search
    listener:
      missing-topics-fatal: false

elasticsearch:
  url:
    - 192.168.43.131:9200
  scheme: http
server:
  port: 8082
